apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
    tag: {{.Values.image.tag}}
  name: {{.Values.image.repository}}
  namespace: {{.Values.namespace}}
spec:
  ports:
  - port: {{.Values.service.port}}
    protocol: TCP
    targetPort: {{.Values.service.port}}
  selector:
    app: {{.Values.image.name}}
    tag: {{.Values.image.tag}}
  type: {{.Values.service.type}}


