namespace:
  name: dev
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
  name: nginx-helm-app

resources:
   requests:
      cpu:50m
      mmemory:256Mi

replicaCount: 3

service:
   type:
     ClusterIP
   port: 8111

configMap:
   data:
     versionn: alpine
