namespace: staging
 
image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent
  name: nginx-helm-app

resources:
   requests:
      cpu:100m
      mmemory:512Mi

replicaCount: 6

service:
   type:
     ClusterIP
   port: 8111

configMap:
   data:
     versionn: alpine
