namespace:
  name: demo

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

resources:
   requests:
      cpu:70m
      mmemory:256Mi

replicaCount: 5

configMap:
  data:
     version: 1.17.0

service:
   port: 80
