namespace:
  name: staging

image:
  repository: nginx
  tag: 1.18.0
  pullPolicy: IfNotPresent

resources:
   requests:
      cpu:70m
      mmemory:256Mi

replicaCount: 1

configMap:
  data:
     version: 1.18.0

